'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Sub\cf0  AddStartup(\cf1 ByVal\cf0  Name \cf1 As\cf0  \cf1 String\cf0 , \cf1 ByVal\cf0  Path \cf1 As\cf0  \cf1 String\cf0 )\par
        '''        \cf1 Dim\cf0  Registry \cf1 As\cf0  Microsoft.Win32.RegistryKey = Microsoft.Win32 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property AddStartup() As String
            Get
                Return ResourceManager.GetString("AddStartup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        '''&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        '''&lt;title&gt;Ascii Character Codes&lt;/title&gt;
        '''&lt;table id=&quot;dlOut&quot; style=&quot;border-color: Black; border-collapse: collapse;&quot; border=&quot;0&quot; cellpadding=&quot;5&quot; cellspacing=&quot;0&quot;&gt;
        '''	&lt;tbody&gt;&lt;tr&gt;
        '''		&lt;td&gt;
        '''                  &lt;/td&gt;&lt;td align=&quot;center&quot; bgcolor=&quot;#f5f5dc&quot;&gt;
        '''                     33&lt;/td&gt;
        '''                  &lt;td align=&quot;center&quot; bgcolor=&quot;#f5f5dc&quot;&gt;
        '''                     &lt;b&gt;!&lt;/b&gt;&lt;/td&gt;
        '''                  &lt;td&gt;
        '''                     &amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;n [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Ascii_Codes() As String
            Get
                Return ResourceManager.GetString("Ascii_Codes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  Binary(\cf1 ByVal\cf0  Text \cf1 As\cf0  \cf1 String\cf0 , \cf1 Optional\cf0  \cf1 ByVal\cf0  Reverse \cf1 As\cf0  \cf1 Boolean\cf0  = \cf1 False\cf0 ) \cf1 As\cf0  \cf1 String [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Binary() As String
            Get
                Return ResourceManager.GetString("Binary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\f0\fs20     \cf1 Declare\cf0  \cf1 Sub\cf0  BlockInput \cf1 Lib\cf0  \cf2 &quot;User32&quot;\cf0  (\cf1 ByVal\cf0  Setting \cf1 As\cf0  \cf1 Boolean\cf0 )\par
        '''\par
        '''        \cf3 &apos;Usage\par
        '''\cf0         BlockInput(\cf1 True\cf0 ) \cf3 &apos;Disables mouse [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BlockInput() As String
            Get
                Return ResourceManager.GetString("BlockInput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Dim\cf0  Point \cf1 As\cf0  \cf1 New\cf0  System.Drawing.Point()\par
        '''    \cf1 Dim\cf0  X, Y \cf1 As\cf0  \cf1 Integer\par
        '''\cf0\par
        '''    \cf1 Private\cf0  \cf1 Sub\cf0  Me_MouseDown(\cf1 ByVal\cf0  sender \cf1 As\cf0  System.Object, \cf1 ByVal\cf0  e \cf1 As\cf0  System.Windows.Forms.MouseEvent [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BorderlessForm() As String
            Get
                Return ResourceManager.GetString("BorderlessForm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  ChanceSuccess(\cf1 ByVal\cf0  Chance \cf1 As\cf0  \cf1 Double\cf0 ) \cf1 As\cf0  \cf1 Boolean\par
        '''\cf0         \cf1 Dim\cf0  Random \cf1 As\cf0  \cf1 New\cf0  Random\par
        '''        \cf1 Return\cf0  Random.Next(1, 1000000) / 1000 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ChanceSuccess() As String
            Get
                Return ResourceManager.GetString("ChanceSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  ConvertIP(\cf1 ByVal\cf0  Address \cf1 As\cf0  \cf1 String\cf0 , \cf1 ByVal\cf0  LongIP \cf1 As\cf0  \cf1 Boolean\cf0 ) \cf1 As\cf0  \cf1 Object\par
        '''\cf0         \cf1 Dim\cf0  Data \cf1 As\cf0  \cf1 Stri [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ConvertIP() As String
            Get
                Return ResourceManager.GetString("ConvertIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  CountWords(\cf1 ByVal\cf0  Text \cf1 As\cf0  \cf1 String\cf0 ) \cf1 As\cf0  \cf1 Integer\par
        '''\cf0         \cf1 Dim\cf0  Regex \cf1 As\cf0  \cf1 New\cf0  System.Text.RegularExpressions.Regex(\cf2 &quot;\\w+&quot;\c [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CountWords() As String
            Get
                Return ResourceManager.GetString("CountWords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Dim\cf0  Data \cf1 As\cf0  \cf1 Boolean\cf0  \cf2 &apos;True or False\par
        '''\par
        '''\cf0     \cf1 Dim\cf0  Data \cf1 As\cf0  \cf1 Byte\cf0  \cf2 &apos;0 to 255 (unsigned)\par
        '''\par
        '''\cf0     \cf1 Dim\cf0  Data \cf1 As\cf0  \cf1 Char\cf0  \cf2 &apos;0 to 65535 (unsigned)\par
        '''\par
        '''\cf0     \c [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DataTypes() As String
            Get
                Return ResourceManager.GetString("DataTypes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;\red163\green21\blue21;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  EndProcess(\cf1 ByVal\cf0  Name \cf1 As\cf0  \cf1 String\cf0 , \cf1 Optional\cf0  \cf1 ByVal\cf0  All \cf1 As\cf0  \cf1 Boolean\cf0  = \cf1 True\cf0 ) \cf1 As\cf0  \cf1 Boolean\par
        '''\cf0         \cf1 Dim\ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EndProcess() As String
            Get
                Return ResourceManager.GetString("EndProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Sub\cf0  Fade(\cf1 ByVal\cf0  Form \cf1 As\cf0  Windows.Forms.Form, \cf1 ByVal\cf0  Reverse \cf1 As\cf0  \cf1 Boolean\cf0 , \cf1 Optional\cf0  \cf1 ByVal\cf0  Rate \cf1 As\cf0  \cf1 Integer\cf0  = 20, \cf1 Optional\cf0  \cf1 ByVal\cf0  Minim [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Fade() As String
            Get
                Return ResourceManager.GetString("Fade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  GenerateSerial(\cf1 Optional\cf0  \cf1 ByVal\cf0  Length \cf1 As\cf0  \cf1 Integer\cf0  = 15) \cf1 As\cf0  \cf1 String\par
        '''\cf0         \cf1 If\cf0  Length &gt; 32 \cf1 Then\cf0  Length = 32\par
        '''        \c [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GenerateSerial() As String
            Get
                Return ResourceManager.GetString("GenerateSerial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\f0\fs20     \cf1 Private\cf0  \cf1 Declare\cf0  \cf1 Function\cf0  GetAsyncKeyState \cf1 Lib\cf0  \cf2 &quot;user32&quot;\cf0  (\cf1 ByVal\cf0  Key \cf1 As\cf0  \cf1 Long\cf0 ) \cf1 As\cf0  \cf1 Integer\par
        '''\cf0     \cf1 Private\cf0  \cf1 Declare\cf0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GetKey() As String
            Get
                Return ResourceManager.GetString("GetKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  GetPercent(\cf1 ByVal\cf0  Divisor \cf1 As\cf0  \cf1 Integer\cf0 , \cf1 ByVal\cf0  Multiplier \cf1 As\cf0  \cf1 Integer\cf0 , \cf1 Optional\cf0  \cf1 ByVal\cf0  Decimals \cf1 As\cf0  \cf1 Integer\cf0  = 0) \cf1 As\cf0  \cf1 Dou [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GetPercent() As String
            Get
                Return ResourceManager.GetString("GetPercent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  MachineID() \cf1 As\cf0  \cf1 String\par
        '''\cf0         \cf1 Dim\cf0  Identifier \cf1 As\cf0  \cf1 String\cf0  = \cf1 Nothing\par
        '''\cf0         \cf1 Dim\cf0  Manager \cf1 As\cf0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MachineID() As String
            Get
                Return ResourceManager.GetString("MachineID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20         \cf1 Dim\cf0  Number \cf1 As\cf0  \cf1 Double\par
        '''\par
        '''\cf0         \cf2 &apos;Rounding\par
        '''\cf0         Number = Math.Round(10.5, 0)\par
        '''\par
        '''        \cf2 &apos;Multiplication\par
        '''\cf0         Number = 10 * 5\par
        '''\par
        '''        \cf2 &apos;Division\par
        '''\cf0         Number = 10 / 5\pa [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Math() As String
            Get
                Return ResourceManager.GetString("Math", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  MD5(\cf1 ByVal\cf0  Text \cf1 As\cf0  \cf1 String\cf0 , \cf1 Optional\cf0  \cf1 ByVal\cf0  Seperator \cf1 As\cf0  \cf1 String\cf0  = \cf1 Nothing\cf0 ) \cf1 As\cf0  \cf1 String\par
        '''\cf0         \cf1 Dim\ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property MD5() As String
            Get
                Return ResourceManager.GetString("MD5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;\red163\green21\blue21;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  ObjectType(\cf1 ByVal\cf0  Variable \cf1 As\cf0  \cf1 Object\cf0 ) \cf1 As\cf0  \cf1 String\par
        '''\cf0         \cf1 Return\cf0  Microsoft.VisualBasic.Information.TypeName(Variable)\par
        '''\pard     \cf1 End\ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ObjectType() As String
            Get
                Return ResourceManager.GetString("ObjectType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  ParseIP(\cf1 ByVal\cf0  Text \cf1 As\cf0  \cf1 String\cf0 ) \cf1 As\cf0  \cf1 String\par
        '''\cf0         \cf1 Dim\cf0  Regex = \cf1 New\cf0  System.Text.RegularExpressions.Regex(\cf2 &quot;\\b(?:\\d\{1,3\}\\.)\{ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ParseIP() As String
            Get
                Return ResourceManager.GetString("ParseIP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;\red163\green21\blue21;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  ParseLines(\cf1 ByVal\cf0  Text \cf1 As\cf0  \cf1 String\cf0 ) \cf1 As\cf0  \cf1 String\cf0 ()\par
        '''        \cf1 Return\cf0  Text.Split(Constants.vbLf.ToCharArray)\par
        '''\pard     \cf1 End\cf0  \cf1 Functi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ParseLines() As String
            Get
                Return ResourceManager.GetString("ParseLines", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;\red163\green21\blue21;}
        '''{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  RandomOutput(\cf1 ByVal\cf0  Length \cf1 As\cf0  \cf1 Integer\cf0 , \cf1 ByVal\cf0  Type \cf1 As\cf0  \cf1 Integer\cf0 ) \cf1 As\cf0  \cf1 String\par
        '''\cf0         \cf2 &apos;Delay  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property RandomOutput() As String
            Get
                Return ResourceManager.GetString("RandomOutput", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;\red163\green21\blue21;}
        '''{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  ResolveDNS(\cf1 ByVal\cf0  Host \cf1 As\cf0  \cf1 String\cf0 ) \cf1 As\cf0  \cf1 String\par
        '''\cf0         \cf1 Dim\cf0  Entry \cf1 As\cf0  Net.IPHostEntry = Net.Dns.GetHostEntr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ResolveDNS() As String
            Get
                Return ResourceManager.GetString("ResolveDNS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;\red163\green21\blue21;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  ScanPort(\cf1 ByVal\cf0  Address \cf1 As\cf0  \cf1 String\cf0 , \cf1 ByVal\cf0  Port \cf1 As\cf0  \cf1 Integer\cf0 , \cf1 Optional\cf0  \cf1 ByVal\cf0  Timeout \cf1 As\cf0  \cf1 Integer\cf0  = 500) \cf1 A [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ScanPort() As String
            Get
                Return ResourceManager.GetString("ScanPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;\red163\green21\blue21;}
        '''{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  Scramble(\cf1 ByVal\cf0  Text \cf1 As\cf0  \cf1 String\cf0 , \cf1 Optional\cf0  \cf1 ByVal\cf0  Reverse \cf1 As\cf0  \cf1 Boolean\cf0  = \cf1 False\cf0 ) \cf1 As\cf0  \cf1 Stri [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Scramble() As String
            Get
                Return ResourceManager.GetString("Scramble", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Sub\cf0  SendGmail(\cf1 ByVal\cf0  SenderGmail \cf1 As\cf0  \cf1 String\cf0 , \cf1 ByVal\cf0  SenderPassword \cf1 As\cf0  \cf1 String\cf0 , \cf1 ByVal\cf0  ReceiverEmail \cf1 As\cf0  \cf1 String\cf0 , \cf1 ByVal\cf0  M [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SendGmail() As String
            Get
                Return ResourceManager.GetString("SendGmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\f0\fs20     \cf1 Private\cf0  \cf1 Declare\cf0  \cf1 Auto\cf0  \cf1 Function\cf0  SystemParametersInfo \cf1 Lib\cf0  \cf2 &quot;user32.dll&quot;\cf0  (\cf1 ByVal\cf0  uAction \cf1 As\cf0  \cf1 Integer\cf0 , \cf1 ByVal\cf0  uParam \cf1 As\cf0  \cf1 Int [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SetWallpaper() As String
            Get
                Return ResourceManager.GetString("SetWallpaper", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Sub\cf0  Sleep(\cf1 ByVal\cf0  Delay \cf1 As\cf0  \cf1 Integer\cf0 )\par
        '''        \cf1 For\cf0  I = 1 \cf1 To\cf0  Delay\par
        '''            Application.DoEvents()\par
        '''            Threading.Thread.Sleep(1)\par
        '''        \cf1 Next\par
        '''\pard\cf0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Sleep() As String
            Get
                Return ResourceManager.GetString("Sleep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;\red163\green21\blue21;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  Swap(\cf1 ByVal\cf0  Text \cf1 As\cf0  \cf1 String\cf0 ) \cf1 As\cf0  \cf1 String\par
        '''\cf0         \cf1 Dim\cf0  Store \cf1 As\cf0  \cf1 String\cf0  = \cf1 Nothing\par
        '''\cf0         \cf1 For\cf0  \cf1 Ea [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Swap() As String
            Get
                Return ResourceManager.GetString("Swap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Sub\cf0  TextToSpeech(\cf1 ByVal\cf0  Text \cf1 As\cf0  \cf1 String\cf0 , \cf1 Optional\cf0  \cf1 ByVal\cf0  Rate \cf1 As\cf0  \cf1 Integer\cf0  = 0)\par
        '''        \cf1 Dim\cf0  TTS \cf1 As\cf0  \cf1 Object\cf0  = Creat [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TextToSpeech() As String
            Get
                Return ResourceManager.GetString("TextToSpeech", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;\red163\green21\blue21;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  TripleDES(\cf1 ByVal\cf0  Text \cf1 As\cf0  \cf1 String\cf0 , \cf1 ByVal\cf0  Password \cf1 As\cf0  \cf1 String\cf0 , \cf1 Optional\cf0  \cf1 ByVal\cf0  Reverse \cf1 As\cf0  \cf1 Boolean\cf0  = \cf1 False [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property TripleDES() As String
            Get
                Return ResourceManager.GetString("TripleDES", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  UTF8(\cf1 ByVal\cf0  Text \cf1 As\cf0  \cf1 String\cf0 ) \cf1 As\cf0  \cf1 String\par
        '''\cf0         \cf1 Dim\cf0  Value \cf1 As\cf0  \cf1 Byte\cf0 () = System.Text.Encoding.UTF8.GetBytes(Text)\par
        '''       [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UTF8() As String
            Get
                Return ResourceManager.GetString("UTF8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  ValidateConnection(\cf1 Optional\cf0  \cf1 ByVal\cf0  URL \cf1 As\cf0  \cf1 String\cf0  = \cf2 &quot;http://www.Microsoft.com/&quot;\cf0 ) \cf1 As\cf0  \cf1 Boolean\par
        '''\cf0         \cf [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ValidateConnection() As String
            Get
                Return ResourceManager.GetString("ValidateConnection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  ValidateEmail(\cf1 ByVal\cf0  Email \cf1 As\cf0  \cf1 String\cf0 ) \cf1 As\cf0  \cf1 Boolean\par
        '''\cf0         \cf1 Dim\cf0  Expression \cf1 As\cf0  \cf1 New\cf0  System.Text.RegularExpressions.Regex(\cf2 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ValidateEmail() As String
            Get
                Return ResourceManager.GetString("ValidateEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red163\green21\blue21;\red0\green128\blue0;}
        '''\viewkind4\uc1\pard\lang1024\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  ValidateFile(\cf1 ByVal\cf0  Filename \cf1 As\cf0  \cf1 String\cf0 ) \cf1 As\cf0  \cf1 Boolean\par
        '''\cf0         \cf1 Dim\cf0  Expression \cf1 As\cf0  \cf1 New\cf0  System.Text.RegularExpressions.Regex(\c [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ValidateFile() As String
            Get
                Return ResourceManager.GetString("ValidateFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\deflang1033{\fonttbl{\f0\fnil\fprq1\fcharset0 Courier New;}{\f1\fnil\fcharset0 Microsoft Sans Serif;}}
        '''{\colortbl ;\red0\green0\blue255;\red0\green128\blue0;\red163\green21\blue21;}
        '''{\*\generator Msftedit 5.41.15.1515;}\viewkind4\uc1\pard\f0\fs20     \cf1 Public\cf0  \cf1 Shared\cf0  \cf1 Function\cf0  ValidatePassword(\cf1 ByVal\cf0  Password \cf1 As\cf0  \cf1 String\cf0 , \cf1 Optional\cf0  \cf1 ByVal\cf0  Minimum \cf1 As\cf0  \cf1 Integer\cf0  = 6) \cf1 As\cf0  \cf1 Intege [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ValidatePassword() As String
            Get
                Return ResourceManager.GetString("ValidatePassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        '''&lt;html&gt;&lt;head&gt;&lt;title&gt;Virtual Key Codes&lt;/title&gt;
        '''&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=Windows-1251&quot;&gt;
        '''&lt;/head&gt;&lt;body&gt;
        '''
        '''&lt;h1&gt;Virtual Key Codes&lt;/h1&gt;
        '''
        '''&lt;div class=&quot;shortdescr&quot;&gt;
        '''The following table shows the symbolic constant names, hexadecimal values,
        '''and mouse or keyboard equivalents for the &lt;a href=&quot;http://msdn.microsoft.com/library/en-us/winui/WinUI/WindowsUserInterface/UserInput/VirtualKeyCodes.asp&quot;&gt;Virtual-Key Codes&lt;/a&gt;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Virtual_Key_Codes() As String
            Get
                Return ResourceManager.GetString("Virtual_Key_Codes", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
